server:
  hostname: localhost
  port: ${CRYPTO_APP_PORT}
  eureka-port: ${EUREKA_DISCOVERY_PORT}

spring:
  application:
    name: crypto-ms

  profiles:
    active: "development"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${server.hostname}:${CRYPTO_DB_PORT}/${CRYPTO_DB_DATABASE}
    username: ${CRYPTO_DB_USER}
    password: ${CRYPTO_DB_USER}

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
        format_sql: true

eureka:
  instance:
    hostname: ${server.hostname}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${server.hostname}:${server.eureka-port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"