server:
  port: 8086

spring:
  application:
    name: spring_kafka_product

  datasource:
    url: jdbc:mysql://localhost:3308/productdb
    username: myuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    default-property-inclusion: NON_NULL

  kafka:
    bootstrap-servers: host.docker.internal:9092
    consumer:
      group-id: my-group-id

springdoc:
  override-with-generic-response: false
  api-docs:
    path: /docs/api
  swagger-ui:
    path: /docs/index.html