server:
  port: ${DISCOVERY_APP_PORT}

spring:
  application:
    name: discovery-ms

  profiles:
    active: "development"

  cloud:
    config:
      enabled: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
