// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/addressbook.proto

package com.example.protobuf.models;

public interface CourseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.Course)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string course_name = 2;</code>
   * @return The courseName.
   */
  java.lang.String getCourseName();
  /**
   * <code>string course_name = 2;</code>
   * @return The bytes for courseName.
   */
  com.google.protobuf.ByteString
      getCourseNameBytes();

  /**
   * <code>repeated .protobuf.Student student = 3;</code>
   */
  java.util.List<com.example.protobuf.models.Student> 
      getStudentList();
  /**
   * <code>repeated .protobuf.Student student = 3;</code>
   */
  com.example.protobuf.models.Student getStudent(int index);
  /**
   * <code>repeated .protobuf.Student student = 3;</code>
   */
  int getStudentCount();
  /**
   * <code>repeated .protobuf.Student student = 3;</code>
   */
  java.util.List<? extends com.example.protobuf.models.StudentOrBuilder> 
      getStudentOrBuilderList();
  /**
   * <code>repeated .protobuf.Student student = 3;</code>
   */
  com.example.protobuf.models.StudentOrBuilder getStudentOrBuilder(
      int index);
}
